#' ROC curve for input data
#'
#' @param input_df input_df
#' @param input_variables input_variables
#' @param input_category input_category
#' @param levels levels
#' @param direction direction
#' @param smooth smooth
#'
#' @return list contains roc and auc
#' @export
#'
fun_roc = function(input_df,input_variables,input_category = "binaryResponse",levels = NULL, direction="auto",smooth = FALSE){

  if(is.null(levels)){
    levels = levels(as.factor(input_df[[input_category]]))
  }
  message(paste0(levels,collapse = " - "))
  # 2) roc
  r_res = pROC::roc(input_df[[input_category]],
                    input_df[[input_variables]],
              levels = levels,
              direction = direction,
              smooth=smooth)

  # 3) plot
  roc = data.frame(
    fpr = 1-r_res$specificities,
    tpr = r_res$sensitivities,
    variable = input_category
  ) %>%
    dplyr::arrange(tpr,fpr)
  auc = r_res$auc %>% stringr::str_replace("Area under the curve:","") %>% as.numeric()
  return(
    list(roc = roc,
         auc = auc)
  )
}


#' ROC plot
#'
#' @param input_roc input_roc list generated by fun_roc
#' @param legend.position legend.position
#' @param title title
#' @param palette palette
#' @param digits
#'
#' @return ggplot obj
#' @export
#'
fun_plot_roc = function(input_roc,legend.position = c(0.7,0.2),title = NULL,palette = c("black"),digits = 2){
  # the input data should be roc list
  # with roc
  # and auc
  # auc character
  # legend
  legend_text = paste0("AUC = ",format(round(input_roc$auc,digits),digits=digits))

  # roc plot
  ggplot2::ggplot(input_roc$roc) +
    ggplot2::geom_line(ggplot2::aes(x = fpr,y = tpr))+
    ggplot2::geom_abline(slope =1,color = "gray")+
    # line
    ggplot2::theme_bw()+
    ggplot2::theme(panel.grid = ggplot2::element_blank(),
          legend.background = ggplot2::element_blank(),
          legend.position = legend.position )+
    ggplot2::labs(x = "1 - Specificity",
         y = "Sensitivity",
         title=title)+
    ggplot2::scale_x_continuous(expand = c(0.005,0.005))+
    ggplot2::scale_y_continuous(expand = c(0.005,0.005))+
    ggplot2::coord_fixed()+
    ggplot2::annotate("text",label = legend_text,
             x = legend.position[1],
             y = legend.position[2])

}

